routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Carbon\Carbon;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('layouts.layout');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::resource('roles',App\Http\Controllers\RoleController::class);


Route::get('/carbontime',function (){
    $ryan =Carbon::now('Europe/Amsterdam');
    echo $ryan->format('d-m-Y');

});
Route::resource('tabletopgames', \App\Http\Controllers\TabletopGameController::class);

app/Models/Role.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Role extends Model
{
    use HasFactory;

    public function userRole()
    {
        return $this->hasMany(User::class);
    }
//    protected $casts =[
//        'updated_at' => 'd-m-Y'
//        ];
}

app/Http/Controllers/RoleController.php
<?php

namespace App\Http\Controllers;

use App\Models\Role;
use App\Http\Requests\StoreRoleRequest;
use App\Http\Requests\UpdateRoleRequest;
use Illuminate\Support\Carbon;

class RoleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
       $roles = Role::orderBy('updated_at','desc')->get();
       $newYear = new Carbon('first day of January 2023');
       return view('roles.index', compact('roles','newYear'));
    }


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('roles.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\StoreRoleRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreRoleRequest $request)
    {
//        return $request;
        $role = new Role();
        $role->title = $request->title;
        $role->save();
        return redirect('roles');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Role  $role
     * @return \Illuminate\Http\Response
     */
    public function show(Role $role)
    {
        return view('roles.show', compact('role'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Role  $role
     * @return \Illuminate\Http\Response
     */
    public function edit(Role $role)
    {
        return view('roles.edit', compact('role'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\UpdateRoleRequest  $request
     * @param  \App\Models\Role  $role
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateRoleRequest $request, Role $role)
    {
        $role = Role::find($role->id);

        $role->title = $request->title;
        $role->save();
        return redirect('roles');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Role  $role
     * @return \Illuminate\Http\Response
     */
    public function destroy(Role $role)
    {
        $role->delete();
        return redirect('roles');
    }

}

resources/views/roles/create.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">
                        <h1>Create</h1>
                    </div>

                    <div class="card-body">
                        <form action="{{ route('roles.store') }}"method="post">
                            @csrf
                            <label for="title">Rolnaam</label>
                            <input type="text" name="title" id="title">
                            <button type="submit">Voeg toe</button>
                        </form>
                    </div>
                </div>


            </div>
        </div>
    </div>
@endsection

resources/views/roles/edit.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">
                        <h1>Edit</h1>
                    </div>

                    <div class="card-body">
                        <form action="{{ route('roles.update', $role->id) }}"method="post">
                            @csrf
                            @method('patch')
                            <label for="title">Rolnaam</label>
                            <input type="text" name="title" id="title" value="{{ $role->title }}">
                            <button class="btn btn-outline-primary btn-sm" type="submit">edit</button>
                        </form>
                    </div>
                </div>


            </div>
        </div>
    </div>
@endsection

resources/views/roles/index.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">
                        <h1>Rollen</h1>
                        <a class="btn btn-outline-info btn-sm" href="{{ route('roles.create') }}">Maak rol</a>
                    </div>

                    <div class="card-body">
                        <ul class="list-group">
                            @foreach($roles as $role)
                                <li class="list-group-item">
                                    <a href="{{ route('roles.show', $role->id) }}">{{ $role->title }}</a>
{{--                                    <p>{{ $role->toArray()['updated_at'] }}</p>--}}
{{--                                    <p>{{ $role->updated_at }}</p>--}}
{{--                                    {{ $newYear->locale('nl')->dayName }}--}}

                                    <form class="float-end" style="display:inline-block" action="{{ route('roles.destroy', $role->id) }}" method="post"> @csrf @method('delete')
                                        <button class="btn btn-outline-danger btn-sm m-1" type="submit"><i class="fa-solid fa-trash-can"></i></button>
                                    </form>
                                    <a class="btn btn-outline-info btn-sm float-end m-1" href="{{ route('roles.edit', $role->id) }}"><i class="fa-solid fa-pen-to-square"></i></a>
                                </li>
                            @endforeach
                        </ul>
                    </div>
                </div>


            </div>
        </div>
    </div>
@endsection

resources/views/roles/show.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">
                        <h1>{{ $role->title }}</h1>
                    </div>

                    <div class="card-body">
                        <ul>
                            @foreach($role->userRole as $user)
                                <li>{{ $user->name }}</li>
                            @endforeach
                        </ul>
                    </div>
                </div>


            </div>
        </div>
    </div>
@endsection